id: I8B8B6D8D
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T04:20:54.938957'
last_modified: '2022-06-19T04:20:54.938970'
parser: null
source_metadata:
  title: Supplement to the History of the Abbots of Ngor E waṃ chos ldan; Lamdre Tshogshe,
    vol. ya, title no. 5
  author: dpal ldan chos skyong /
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2013-09-12); pagination incomplete (pp. 596-651), unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - 'Digital edition: Sakya Research Centre (src)'
  - Text input:rdzong sar khams bye'i lnga rig slob gling / sde dge rdzong sar/ (dzkj)
  - Editorial process:Mathias Fermer (mf), kun dga' rdo rje/ (Kathmandu) (kun)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/590
  bases:
    74d9:
      title: Supplement to the History of the Abbots of Ngor E waṃ chos ldan; Lamdre
        Tshogshe, vol. ya, title no. 5
      order: 1
      base_file: 74d9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
